version: 2

updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/docs"
      - "/packages/**/*"
    schedule:
      interval: "weekly"
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
      graphql:
        patterns:
          - "@apollo/*"
          - "mercurius"
          - "graphql"
      documentation:
        patterns:
          - "@docusaurus/*"
          - "docusaurus*"
          - "*react*"
  
