export const TRANSACTION_CONNECTION = Symbol('TRANSACTION_CONNECTION');
export const TRANSACTIONAL_CLIENT = Symbol('TRANSACTIONAL_CLIENT');
export const TRANSACTIONAL_OPTIONS = Symbol('TRANSACTIONAL_OPTIONS');
