export const TRANSACTION_CONNECTION = Symbol('TRANSACTION_CONNECTION');
export const TRANSACTIONAL_INSTANCE = Symbol('TRANSACTIONAL_CLIENT');
export const TRANSACTIONAL_ADAPTER_OPTIONS = Symbol('TRANSACTIONAL_OPTIONS');
