name: Run tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: test-${{ github.ref }}

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci --audit=false
      - run: npm run lint
      - run: npm run test
