name: Run tests

permissions:
  contents: read

on:
  workflow_dispatch:
  merge_group:
  pull_request:
    branches:
      - main
      - release/*

concurrency:
  cancel-in-progress: true
  group: test-${{ github.ref }}

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}.x
          cache: yarn
      - run: yarn
      - run: yarn build
      - run: yarn lint
      - run: yarn test
