name: Run tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - release/*

concurrency:
  cancel-in-progress: true
  group: test-${{ github.ref }}

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}.x
          cache: npm
      - run: npm ci --audit=false
      - run: npm run lint
      - run: npm run test
